### ISSUE TITLE
2.0 beta not working anymore

### ISSUE THREAD

**Issue by mcr-ksh** [odinb/bash-plexamp-installer#1]
`error: DEVICE: Error loading media providers from plex.tv: Error: Request failed with status code 406
error: DEVICE: Error loading providers or resources, not merging.
warn: DEVICE: Did not find a working server.
`

also using the 1.1.0 client on mac no libraries are found. I guess this is it to the old install.

**Comment by odinb** [comment]
Hi! Currently this script is broken due to updates of how the authentication happens with the plex-server, and it does not look like that will be fixed, see more here:
https://forums.plex.tv/t/plexamp-raspberry-pi-certificate-expired/747294

But looks like a new version of this client is in the works:
https://forums.plex.tv/t/future-of-plexamp-on-raspberry-pi/717577

**Comment by mcr-ksh** [comment]
appreciate the fast response. This is not due to the DST root certificate. I have no error like that. Rather the `Error loading media providers from plex.tv` which is status 406 = not acceptable. some API error. Does it work for you atm?
The last message in the first thread also states the 406

**Comment by odinb** [comment]
New Plexamp Headless v4.2.2 beta has been released, resolving these issues. Bash has been updated to install this newer version.
