### ISSUE TITLE
Default Audio out changes after reboot

### ISSUE THREAD

**Issue by memoriesofmotion** [odinb/bash-plexamp-installer#11]
Good evening,

I would like to start out with telling you how awesome this wright up is and how easy the setup was.  I would also like to say that I will get you any data I can as well as help any way I can.

Problem:  I hard power off my Pi along with my speakers and amp.  When it powers back up and my plex amp streaming target shows back up in my plex amp app, I am unable to play music to it.  It looks like plex amp defaults back to another audio interface and the only way to fix this is to go into the plex amp web interface, disconnect from the streaming target, and change the audio output device back to my BOSS DAC.  Any assistance to hard set the audio device or fix this issue would be appreciated.  

My build: 
-RBP 4 (2gig) 
-Boss DAC HiFi [Master] pcm512x-hifi-0 : Boss DAC HiFi [Master] pcm512x-hi

outputs:
pi@raspberrypi:~ $ cat /proc/asound/modules
 0 snd_soc_allo_boss_dac
 1 vc4
 2 vc4
pi@raspberrypi:/boot $ cat /proc/asound/pcm
00-00: Boss DAC HiFi [Master] pcm512x-hifi-0 : Boss DAC HiFi [Master] pcm512x-hifi-0 : playback 1
01-00: MAI PCM i2s-hifi-0 : MAI PCM i2s-hifi-0 : playback 1
02-00: MAI PCM i2s-hifi-0 : MAI PCM i2s-hifi-0 : playback 1

Config.txt includes this at the end:
dtoverlay=allo-boss-dac-pcm512x-audio

**Comment by odinb** [comment]
Looks like all is configured correct, you can verify that this is the DAC you have: https://www.amazon.com/clouddrive/share/KigTwkJLrzfZlgVQsjE4rXEl6HaQCU0hGFp0B4DPsdV/VYHnWqqaSxq6x41v7hUsIA

You can see the config on the last page of the pdf.

What happens if you leave/choose “Follows system output” or “default” depending on what page you look at in the web-GUI? Does it work then?
