### ISSUE TITLE
Question: Help with other sound drivers / DAC HATs

### ISSUE THREAD

**Issue by newelement** [odinb/bash-plexamp-installer#24]
I'm looking to use Ian Canada's ESS DAC found here:

[https://github.com/iancanada/DocumentDownload/blob/master/RPiDacHAT/ES9038Q2MDualMonoDacHAT/ES9038Q2MPiDualMonoIIManual.pdf](https://github.com/iancanada/DocumentDownload/blob/master/RPiDacHAT/ES9038Q2MDualMonoDacHAT/ES9038Q2MPiDualMonoIIManual.pdf)

The docs state that the Audiophonics driver will work which is found here:

[https://github.com/audiophonics/I-Sabre_9038Q2M](https://github.com/audiophonics/I-Sabre_9038Q2M)

This is probably a bigger topic, but can you provide any help on getting Plexamp to see the driver?

**Comment by newelement** [comment]
Is this where enabling I2S device comes in to play?

**Comment by odinb** [comment]
According to this page: https://www.audiophonics.fr/en/dac-and-interface-modules/ian-canada-dual-mono-mkii-dac-es9038q2m-hat-raspberry-pi-i2s-spdif-pcm-dsd-p-18359.html

All that is needed is to:  "To use the Audiophonics I-SABRE driver with your Rasberry PI, invoke the driver from /boot/config.txt with the command line dtoverlay=i-sabre-q2m or select the "i-sabre-q2m" driver from your Pi-based streaming solution."

This since newer version of the kernel should already have a driver for the 9038Q2M-based audiophonics card as of  Raspberry Linux kernel (V 4.19.34), so no need to install separately, it just needs to be enabled.

Will see if I can get time to add a prompt for that in the next couple of days.

**Comment by newelement** [comment]
Oh sweet how did I miss that part. I have the HAT coming next week. I'll try it. Thanks.

**Comment by newelement** [comment]
With `dtoverlay -a` I'm not seeing that overlay available. Is there another way to check that you know of ?

EDIT - yes it is in there. I was looking for `sabre...` not `i-sabre...`

**Comment by odinb** [comment]
Ok, added option for this card in the script. Let me know if it works!

**Comment by john-pienaar** [comment]
Just to tack on to the above- it would be handy to support the newer Allo Boss 2 DAC:
`DIGICARD="dtoverlay=allo-boss2-dac-audio";;`
Also, thanks for this script!

**Comment by odinb** [comment]
Ok, added the BOSS2 DAC, let me know of any issues! Or if I am missing any other frequently used cards!

**Comment by newelement** [comment]
Reporting back - i-sabre-q2m is working great. Thanks
